### ISSUE TITLE
how to test cronos if spesific cronjob is defined & running?

### ISSUE THREAD

**Issue by hayzem** [mybuilder/cronos-bundle#17]

**Comment by gavinlove** [comment]
Do you mean how to test if cronos know about the annotation or to test if cron is setup correctly?

To test the annotation you can run cronos:dump using the [Symfony command tester](http://symfony.com/doc/current/console.html#testing-commands)  and then search the output for the text you expect to appear in cron.

**Comment by hayzem** [comment]
@gavinlove that's the way I ended up testing cronos.

`        $process = new Process('php app/console cronos:replace');

        try {
            $process->mustRun();
            $output = $process->getOutput();
            $this->assertFalse(strpos($output, 'error'), $output);
        } catch (ProcessFailedException $e) {
            $this->assertTrue(false, $e->getMessage());
        }`
